sample_products=[
  {
    "product_id": "JEANS002",
    "name": "Slim Fit Denim Jeans",
    "description": "Classic slim fit jeans made from premium denim with stretch for comfort. Features a modern cut, five-pocket styling, and durable construction. Perfect for casual wear.",
    "price": 49.99,
    "compare_at_price": 69.99,
    "cost_per_item": 22.50,
    "images": ["https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 0.8,
    "dimensions": { "length": 42, "width": 32, "height": 3 },
    "inventory_quantity": 85,
    "status": "Active"
  },
  {
    "product_id": "HOODIE003",
    "name": "Premium Zip Hoodie",
    "description": "Soft, comfortable hoodie made from cotton blend fabric. Features a front zip, kangaroo pocket, and adjustable drawstring hood. Perfect for cool weather.",
    "price": 39.99,
    "compare_at_price": 59.99,
    "cost_per_item": 18.75,
    "images": ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 0.9,
    "dimensions": { "length": 30, "width": 24, "height": 5 },
    "inventory_quantity": 120,
    "status": "Active"
  },
  {
    "product_id": "SNEAK004",
    "name": "Running Sneakers",
    "description": "Lightweight running shoes with cushioned insoles and breathable mesh uppers. Features a flexible sole for natural movement and excellent traction.",
    "price": 79.99,
    "compare_at_price": 99.99,
    "cost_per_item": 35.00,
    "images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 0.7,
    "dimensions": { "length": 32, "width": 22, "height": 12 },
    "inventory_quantity": 65,
    "status": "Active"
  },
  {
    "product_id": "WATCH005",
    "name": "Classic Chronograph Watch",
    "description": "Elegant timepiece with chronograph functionality, stainless steel case, and genuine leather strap. Water resistant and featuring luminous hands.",
    "price": 129.99,
    "compare_at_price": 179.99,
    "cost_per_item": 65.00,
    "images": ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 0.3,
    "dimensions": { "length": 8, "width": 8, "height": 4 },
    "inventory_quantity": 40,
    "status": "Active"
  },
  {
    "product_id": "BACKPACK006",
    "name": "Waterproof Backpack",
    "description": "Durable backpack made from waterproof nylon with multiple compartments. Features padded laptop sleeve, adjustable straps, and side pockets for bottles.",
    "price": 59.99,
    "compare_at_price": 79.99,
    "cost_per_item": 28.50,
    "images": ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 1.2,
    "dimensions": { "length": 45, "width": 30, "height": 18 },
    "inventory_quantity": 75,
    "status": "Active"
  },
  {
    "product_id": "HEADPH007",
    "name": "Wireless Noise-Canceling Headphones",
    "description": "Premium headphones with active noise cancellation, 30-hour battery life, and comfortable over-ear design. Features Bluetooth connectivity and built-in microphone.",
    "price": 199.99,
    "compare_at_price": 299.99,
    "cost_per_item": 120.00,
    "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 0.5,
    "dimensions": { "length": 20, "width": 18, "height": 10 },
    "inventory_quantity": 55,
    "status": "Active"
  },
  {
    "product_id": "SUNGL008",
    "name": "Polarized Sunglasses",
    "description": "Stylish sunglasses with polarized lenses to reduce glare. Features UV400 protection, lightweight frame, and comes with a protective case.",
    "price": 89.99,
    "compare_at_price": 129.99,
    "cost_per_item": 42.00,
    "images": ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 0.2,
    "dimensions": { "length": 18, "width": 14, "height": 6 },
    "inventory_quantity": 90,
    "status": "Active"
  },
  {
    "product_id": "YOGAMAT009",
    "name": "Eco-Friendly Yoga Mat",
    "description": "Non-toxic yoga mat made from natural rubber with excellent grip. Features a textured surface for stability and comes with a carrying strap.",
    "price": 34.99,
    "compare_at_price": 49.99,
    "cost_per_item": 18.00,
    "images": ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 2.1,
    "dimensions": { "length": 72, "width": 24, "height": 5 },
    "inventory_quantity": 60,
    "status": "Active"
  },
  {
    "product_id": "BLENDER010",
    "name": "High-Speed Blender",
    "description": "Powerful blender with 1500-watt motor and stainless steel blades. Features multiple speed settings, pulse function, and BPA-free pitcher.",
    "price": 149.99,
    "compare_at_price": 199.99,
    "cost_per_item": 85.00,
    "images": ["https://images.unsplash.com/photo-1560343090-f0409e92791a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 5.8,
    "dimensions": { "length": 22, "width": 18, "height": 46 },
    "inventory_quantity": 35,
    "status": "Active"
  },
  {
    "product_id": "DESKLAMP011",
    "name": "LED Desk Lamp",
    "description": "Modern desk lamp with adjustable brightness and color temperature. Features USB charging port, touch controls, and flexible gooseneck design.",
    "price": 45.99,
    "compare_at_price": 69.99,
    "cost_per_item": 22.00,
    "images": ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
    "weight": 1.5,
    "dimensions": { "length": 35, "width": 15, "height": 15 },
    "inventory_quantity": 80,
    "status": "Active"
  },
{
"product_id": "TSHIRT001",
"name": "Classic Cotton T-Shirt",
"description": "Our essential classic t-shirt is made from 100% premium cotton for a soft, comfortable feel. Perfect for everyday wear, it features a modern fit and durable double-stitched sleeves and hem. Available in multiple colors.",
"price": 19.99,
"compare_at_price": 24.99,
"cost_per_item": 8.50,
"images": ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 0.4,
"dimensions": { "length": 28, "width": 20, "height": 2 },
"inventory_quantity": 150,
"status": "Active"
},
{
"product_id": "JEANS002",
"name": "Slim Fit Denim Jeans",
"description": "These slim-fit jeans are crafted from durable denim with just the right amount of stretch for all-day comfort. Features a classic five-pocket design and a modern tapered leg. A versatile staple for any wardrobe.",
"price": 59.99,
"compare_at_price": 79.99,
"cost_per_item": 25.00,
"images": ["https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 1.1,
"dimensions": { "length": 42, "width": 32, "height": 3 },
"inventory_quantity": 85,
"status": "Active"
},
{
"product_id": "SNEAK003",
"name": "UltraBoost Running Shoes",
"description": "Experience maximum energy return and comfort with our UltraBoost running shoes. Featuring a responsive midsole, adaptive knit upper, and a durable rubber outsole for superior grip on any surface. Ideal for running or casual wear.",
"price": 129.99,
"compare_at_price": 159.99,
"cost_per_item": 55.00,
"images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 0.9,
"dimensions": { "length": 32, "width": 22, "height": 12 },
"inventory_quantity": 60,
"status": "Active"
},
{
"product_id": "WATCH004",
"name": "Chronograph Leather Strap Watch",
"description": "A sophisticated timepiece featuring a precise quartz movement, a genuine leather strap, and a sleek stainless steel case. The chronograph function and luminous hands make it both stylish and highly functional.",
"price": 89.99,
"compare_at_price": 120.00,
"cost_per_item": 35.00,
"images": ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 0.3,
"dimensions": { "length": 9, "width": 9, "height": 6 },
"inventory_quantity": 45,
"status": "Active"
},
{
"product_id": "BACKPACK005",
"name": "Explorer 25L Travel Backpack",
"description": "Built for the modern traveler, this 25L backpack features a padded laptop compartment, multiple organizational pockets, and water-resistant material. The ergonomic shoulder straps ensure comfort on the go.",
"price": 74.99,
"compare_at_price": 99.99,
"cost_per_item": 32.00,
"images": ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 1.0,
"dimensions": { "length": 45, "width": 30, "height": 18 },
"inventory_quantity": 75,
"status": "Active"
},
{
"product_id": "MOUSE006",
"name": "Wireless Ergonomic Mouse",
"description": "Work in comfort with this wireless ergonomic mouse designed to reduce wrist strain. Features precise tracking, silent clicks, and a long-lasting battery. Connects via Bluetooth or USB receiver.",
"price": 34.99,
"compare_at_price": 49.99,
"cost_per_item": 14.00,
"images": ["https://images.unsplash.com/photo-1527814050087-3793815479db?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 0.2,
"dimensions": { "length": 11, "width": 7, "height": 4 },
"inventory_quantity": 200,
"status": "Active"
},
{
"product_id": "MUG007",
"name": "Ceramic Coffee Mug (Set of 2)",
"description": "Start your day right with this set of two premium ceramic mugs. They feature a comfortable handle, a large capacity, and a glossy finish. Both are dishwasher and microwave safe.",
"price": 22.99,
"compare_at_price": 29.99,
"cost_per_item": 8.00,
"images": ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 1.2,
"dimensions": { "length": 20, "width": 20, "height": 16 },
"inventory_quantity": 110,
"status": "Active"
},
{
"product_id": "LAMP008",
"name": "Modern Architect Desk Lamp",
"description": "Illuminate your workspace with this sleek, adjustable desk lamp. Its minimalist design features an articulated arm for precise lighting, an LED bulb with 3 brightness levels, and a touch-sensitive base.",
"price": 44.95,
"compare_at_price": 59.95,
"cost_per_item": 18.50,
"images": ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 2.5,
"dimensions": { "length": 40, "width": 15, "height": 15 },
"inventory_quantity": 40,
"status": "Active"
},
{
"product_id": "BOOK009",
"name": "The Complete Coding Interview Guide",
"description": "Ace your next tech interview with this comprehensive guide. Covers data structures, algorithms, system design, and behavioral questions with over 200 practice problems and solutions. A must-have for aspiring software developers.",
"price": 37.50,
"compare_at_price": 45.00,
"cost_per_item": 12.00,
"images": ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 1.0,
"dimensions": { "length": 23, "width": 18, "height": 3 },
"inventory_quantity": 95,
"status": "Active"
},
{
"product_id": "SPEAKER010",
"name": "Portable Bluetooth Speaker",
"description": "Take your music anywhere with this compact, powerful Bluetooth speaker. Delivers rich, clear sound with deep bass, is waterproof, and has a 12-hour battery life. Perfect for outdoor adventures.",
"price": 49.99,
"compare_at_price": 69.99,
"cost_per_item": 22.00,
"images": ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80"],
"weight": 0.7,
"dimensions": { "length": 18, "width": 7, "height": 7 },
"inventory_quantity": 125,
"status": "Active"
}
]
